services:
  starknet-explorer:
    image: public.ecr.aws/o5q6k5w4/stark_compass_explorer:latest
    ports:
      - 4000:4000
    environment:
      - PHX_HOST=localhost
      - PORT=4000
      - RPC_API_HOST=https://juno-kakarot-sepolia.karnot.xyz/
      - TESTNET_RPC_API_HOST=https://juno-kakarot-sepolia.karnot.xyz/
      - SEPOLIA_RPC_API_HOST=https://juno-kakarot-sepolia.karnot.xyz/
      - DISABLE_MAINNET_SYNC=true
      - DISABLE_SEPOLIA_SYNC=true
      - DATABASE_PATH=ecto://postgres:postgres@starknet-explorer-db:5432/starknet_explorer_dev
      - DB_TYPE=postgres
      - SECRET_KEY_BASE=JyULoT5cLBifW+XNEuCTVoAb+SaFgQt9j227RN0cKpR3wTsrApGd1HNcgeopemyl
      - ENABLE_LISTENER=true
    depends_on:
      starknet-explorer-db:
        condition: service_started
    extra_hosts:
      - host.docker.internal_prod:172.17.0.1
    networks:
      - internal_prod

  starknet-explorer-db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starknet_explorer_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - starknet-explorer_prod:/var/lib/postgresql/data/

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: blockscout
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blockscout
    networks:
      - internal_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - internal_prod
    volumes:
      - redis_data_prod:/data

  blockscout:
    image: blockscout/blockscout:latest
    environment:
      DATABASE_URL: postgres://blockscout:postgres@postgres:5432/blockscout
      DATABASE_SSL: "false"
      DATABASE_POOL_SIZE: 10
      DATABASE_TIMEOUT: 5000
      ECTO_USE_SSL: "false"
      BLOCKSCOUT_HOST: 0.0.0.0
      PORT: 4000
      APP_NAME: Blockscout
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_HTTP_URL: http://kakarot-rpc:3030
      ETHEREUM_JSONRPC_TRACE_URL: http://kakarot-rpc:3030
    ports:
      - 4001:4000
    networks:
      - internal_prod
    command:
      [
        /bin/sh,
        -c,
        bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
        && bin/blockscout start,
      ]
    depends_on:
      - postgres
      - redis

  kakarot-rpc:
    image: ghcr.io/kkrt-labs/kakarot-rpc/node:v0.7.0
    pull_policy: always
    ports:
      - 3030:3030
    environment:
      - KAKAROT_RPC_URL=0.0.0.0:3030
      - STARKNET_NETWORK=https://juno-kakarot-sepolia.karnot.xyz/
      - RUST_LOG=kakarot_rpc=debug
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DATABASE_NAME=kakarot-local
      # These values are unique to Sepolia Testnet
      # They'll need to be manually changed in case the testnet is reset
      # To add robustness: parse the `deployments/kakarot-sepolia` folder in `kkrt-labs/kakarot` repo
      - KAKAROT_ADDRESS=0x78bd079b79aa45111313f200a22e5c52ff7526c746d73b65672cc28acbe2263
      - UNINITIALIZED_ACCOUNT_CLASS_HASH=0x5977621f53b7d1b129446775bd7d5a573f8a87297c6287853d52219ffb90c9
      - ACCOUNT_CONTRACT_CLASS_HASH=0x3c64a1702579c371fc47af9231b5537ba2bfbc82834890216dc0bc5688d1810
      - MAX_FELTS_IN_CALLDATA=30000
      - MAX_LOGS=10000
      - WHITE_LISTED_EIP_155_TRANSACTION_HASHES=0xeddf9e61fb9d8f5111840daef55e5fde0041f5702856532cdbb5a02998033d26,0xb6274b80bc7cda162df89894c7748a5cb7ba2eaa6004183c41a1837c3b072f1e,0x07471adfe8f4ec553c1199f495be97fc8be8e0626ae307281c22534460184ed1,0xb95343413e459a0f97461812111254163ae53467855c0d73e0f1e7c5b8442fa3
      - RELAYER_PRIVATE_KEY=${RELAYERS_PRIVATE_KEY}
      - RELAYERS_ADDRESSES=0x02a797bdd904160eb9f7ffefe6ae59abd31d08aae493de453aa55c2950d8c741
    restart: on-failure
    volumes:
      # Mount the indexer code
      - indexer_code_prod:/usr/src/indexer
    networks:
      - internal_prod

  ### MongoDB with Mongo Express
  mongo:
    image: mongo:6.0.8
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data_prod:/data/db
    networks:
      - internal_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  indexer:
    image: quay.io/apibara/sink-mongo:0.7.1
    command:
      - run
      - /indexer/src/main.ts
    environment:
      # Whitelist environment variables
      - ALLOW_ENV_FROM_ENV=DEBUG,APIBARA_AUTH_TOKEN,STARTING_BLOCK,STREAM_URL,SINK_TYPE,MONGO_CONNECTION_STRING,MONGO_DATABASE_NAME,STARKNET_NETWORK,KAKAROT_ADDRESS,ALLOW_NET,MONGO_REPLACE_DATA_INSIDE_TRANSACTION,DEFAULT_BLOCK_GAS_LIMIT
      - DEBUG=""
      - AUTH_TOKEN=${APIBARA_AUTH_TOKEN}
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DATABASE_NAME=kakarot-local
      - STARTING_BLOCK=220000
      - STREAM_URL=https://sepolia.starknet.a5a.ch
      - SINK_TYPE=mongo
      - STARKNET_NETWORK=https://juno-kakarot-sepolia.karnot.xyz/
      - ALLOW_NET=
      - MONGO_REPLACE_DATA_INSIDE_TRANSACTION=false
      - KAKAROT_ADDRESS=0x78bd079b79aa45111313f200a22e5c52ff7526c746d73b65672cc28acbe2263
      - DEFAULT_BLOCK_GAS_LIMIT=7000000
    restart: on-failure
    volumes:
      - indexer_code_prod:/indexer
    networks:
      - internal_prod

networks:
  internal_prod:
    driver: bridge
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  mongo_data_prod:
  indexer_code_prod:
  pgadmin_data_prod:
  juno_files_prod:
  starknet-explorer_prod:
  postgres_data_prod:
  redis_data_prod:
